name: publish

on:
  push:
    branches: ["main"]

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Publish
        run: |
          docker buildx build \
            --tag ghcr.io/${{ env.IMAGE_NAME }}:latest \
            --tag ghcr.io/${{ env.IMAGE_NAME }}:v${{ github.run_number }} \
            --platform linux/amd64,linux/arm64 . \
            --push
